import { sourceTable } from './source-table.js';
import type { Analysis, Entry } from '../analysis.js';
import type { Presentation, TemplateResult } from './template.js';
import { escapeHtml as h, formatNumber, reasonText, shorten, text } from './locale.js';

const copy = {
  uk: { requested: 'Результат для запитаних мов', supplement: 'Додаткове порівняння', unavailable: 'Недоступні запитані мови', none: 'Немає', method: 'Метод і покриття', recent: '3 міс., %', annual: '12 міс., %', relative: 'Частка, %', daily: 'На день', ppm: 'На мільйон', sensitivity: 'Сценарій, в.п.', source: 'Джерела й точні статті', status: 'Повнота початкового запиту', coverage: 'Пари / можливі; покриття', comparison: 'Додаткові мови не замінюють запитані. Міжмовний зв’язок не гарантує однакового змісту й обсягу статей.', methods: 'daily: повні денні вікна. api_monthly: місячні агрегати того самого AQS, повноту днів не доведено. matched_calendar_change: зміна лише на спільних календарних парах, не точне повнорічне зростання. Відсутні дні можуть бути нетиповими; 29 лютого виключено лише в парному сценарії.', graphs: 'Графіки первинних денних сум; пропуски збережено. Резервні місячні агрегати не розподіляються між днями.', quality: 'Суттєві висновки та обмеження', critical: 'Усі коди застережень для всіх рядків', omitted: 'Коротке представлення. Не ввійшли детальні рядки', full: 'Усі 7 видів findings для наведених рядків відображено у таблицях. Повні ряди, виключені дати, інші рядки та знімки: analysis.json / series.csv / source-manifest.json.', selected: 'Причини вибору додаткових мов', base: 'База → поточне', excluded: 'Виключені дати', pages: 'Сторінки', separate: 'Успіх генерації PDF не означає повноти початкового порівняння.' },
  en: { requested: 'Requested languages result', supplement: 'Supplemental comparison', unavailable: 'Unavailable requested languages', none: 'None', method: 'Method and coverage', recent: '3 mo., %', annual: '12 mo., %', relative: 'Share, %', daily: 'Per day', ppm: 'Per million', sensitivity: 'Scenario, pp', source: 'Sources and exact articles', status: 'Original request completion', coverage: 'Pairs / possible; coverage', comparison: 'Supplemental languages do not replace requested languages. Interlanguage links do not guarantee equal article content or scope.', methods: 'daily: complete daily windows. api_monthly: monthly aggregates from the same AQS, not proof of daily completeness. matched_calendar_change: change on shared calendar pairs, not exact full-year growth. Missing days may be atypical; February 29 is excluded only in paired scenarios.', graphs: 'Charts show original daily sums with gaps retained. Monthly residuals are not allocated to days.', quality: 'Material findings and limitations', critical: 'All warning codes for all rows', omitted: 'Short presentation. Detailed rows omitted', full: 'All 7 finding types for displayed rows appear in the tables. Full series, excluded dates, other rows and snapshots: analysis.json / series.csv / source-manifest.json.', selected: 'Supplement selection reasons', base: 'Baseline → current', excluded: 'Excluded dates', pages: 'Pages', separate: 'Successful PDF generation does not imply that the original comparison is complete.' },
  ru: { requested: 'Результат для запрошенных языков', supplement: 'Дополнительное сравнение', unavailable: 'Недоступные запрошенные языки', none: 'Нет', method: 'Метод и покрытие', recent: '3 мес., %', annual: '12 мес., %', relative: 'Доля, %', daily: 'В день', ppm: 'На миллион', sensitivity: 'Сценарий, п.п.', source: 'Источники и точные статьи', status: 'Полнота исходного запроса', coverage: 'Пары / возможные; покрытие', comparison: 'Дополнительные языки не заменяют запрошенные. Межъязыковая связь не гарантирует одинакового содержания и объёма статей.', methods: 'daily: полные дневные окна. api_monthly: месячные агрегаты того же AQS, полнота дней не доказана. matched_calendar_change: изменение на общих календарных парах, не точный годовой рост. Пропуски могут быть нетипичными; 29 февраля исключается только в парном сценарии.', graphs: 'Графики исходных дневных сумм с пропусками. Месячные остатки не распределяются между днями.', quality: 'Существенные выводы и ограничения', critical: 'Все коды предупреждений для всех строк', omitted: 'Краткое представление. Не вошли подробные строки', full: 'Все 7 типов findings показанных строк включены в таблицы. Полные ряды, исключённые даты, другие строки и снимки: analysis.json / series.csv / source-manifest.json.', selected: 'Причины выбора дополнительных языков', base: 'База → текущее', excluded: 'Исключённые даты', pages: 'Страницы', separate: 'Успех генерации PDF не означает полноты исходного сравнения.' },
};
export function buildCompletionHtml(a: Analysis, p: Presentation, charts: { absolute: string; relative: string }, fonts: string): TemplateResult {
  const locale = p.locale, t = text[locale], c = copy[locale], completion = a.completion;
  const requested = completion?.requestedLanguages ?? [...new Set(a.entries.map(e => e.language))], supplemental = completion?.supplementalLanguages ?? [];
  // Всі рядки невеликого дослідження; для великого — ядро/root і явний список скорочення.
  const main = a.topicStudy ? a.entries.filter(e => a.topicStudy!.rows.some(r => r.id === e.id && ['core', 'root'].includes(r.role))) : a.entries;
  const entries = [...new Map([...p.rowIds.map(id => a.entries.find(e => e.id === id)!), ...main].map(e => [e.id, e])).values()].slice(0, 12);
  const omittedRows = a.entries.filter(e => !entries.includes(e)).map(e => e.id);
  const displayedFindings = a.findings.filter(f => entries.some(e => e.id === f.evidenceId));
  const expectedNumbers: string[] = [], requiredText = [c.requested, c.supplement, c.method, c.quality, c.source, a.runId, a.period.start, a.period.end];
  const n = (value: number | null, digits = 1): string => { const s = formatNumber(value, locale, digits); if (value !== null) expectedNumbers.push(s); return h(s); };
  const title = (e: Entry) => `${shorten(a.topics.find(t => t.topicId === e.topicId)!.label, 62)} / ${e.language}`;
  const find = (e: Entry, type: string) => a.findings.find(f => f.evidenceId === e.id && f.type === type)?.value ?? null;
  const table = (rows: Entry[]) => `<table><thead><tr><th>${h(t.row)}</th><th>${h(t.views)}</th><th>${h(c.annual)}</th><th>${h(c.recent)}</th><th>${h(c.relative)}</th></tr></thead><tbody>${rows.map(e => `<tr data-entry-id="${h(e.id)}"><td>${h(title(e))}</td><td>${n(find(e, 'volume'), 0)}</td><td>${n(find(e, 'annual_change'))}</td><td>${n(find(e, 'recent_change'))}</td><td>${n(find(e, 'relative_change'))}</td></tr>`).join('')}</tbody></table>`;
  const warnings = [...new Set([...a.warnings, ...a.findings.flatMap(f => f.warnings), ...a.topicStudy?.languages.flatMap(l => l.quality.flags) ?? []])].sort();
  const explanations: Record<string, string> = {
    MONTHLY_NOT_INDEPENDENT: c.methods, MATCHED_NOT_FULL_YEAR: c.methods,
    DAILY_SENSITIVITY_LIMITED: locale === 'en' ? 'Daily spike sensitivity remains limited by unknown days.' : locale === 'ru' ? 'Проверка дневных всплесков ограничена пропусками.' : 'Перевірка денних сплесків обмежена невідомими днями.',
    ABSOLUTE_RELATIVE_DISAGREEMENT: locale === 'en' ? 'Absolute views and topic share move in different directions.' : locale === 'ru' ? 'Абсолютные просмотры и доля темы меняются разнонаправленно.' : 'Абсолютні перегляди й частка теми змінюються в різних напрямах.',
    ANNUAL_RECENT_DISAGREEMENT: locale === 'en' ? 'Annual and recent changes disagree.' : locale === 'ru' ? 'Годовая и недавняя динамика расходятся.' : 'Річна й нещодавня динаміка суперечать одна одній.',
    MONTHLY_DAILY_DISCREPANCY: locale === 'en' ? 'Monthly and observed daily sums disagree; these aggregates are excluded from fallback.' : locale === 'ru' ? 'Месячные и дневные суммы расходятся; эти агрегаты исключены из резервного расчёта.' : 'Місячні й денні суми розходяться; ці агрегати виключені з резервного розрахунку.',
  };
  const limits = [...new Set(warnings.flatMap(code => reasonText[code]?.[locale] ?? explanations[code] ?? []))];
  const received = [...new Set(a.sources.map(s => s.receivedAt))].sort();
  const footer = `<footer>runId: ${h(a.runId)} · ${h(t.downloaded)}: ${h(received[0] ?? '—')} — ${h(received.at(-1) ?? '—')}</footer>`;
  const methodRows = entries.map(e => {
    const yearly = e.recovery?.yearOverYear, recent = e.recovery?.lastThreeMonths;
    return `<tr><td>${h(title(e))}<br><span class="note">${h(c.excluded)}: ${yearly?.excludedDates.length ?? 0}${yearly?.excludedDates.length ? ` (${h(yearly.excludedDates.slice(0, 4).join(', '))}${yearly.excludedDates.length > 4 ? '; analysis.json' : ''})` : ''}</span></td><td>${h(yearly?.method ?? 'daily')}<br>${h(recent?.method ?? 'daily')}<br><span class="note">${h(t.views)}: ${h(e.recovery?.periodSummary?.method ?? 'daily')}</span></td><td>${n(yearly?.pairedDays ?? 0, 0)} / ${n(yearly?.possiblePairs ?? 0, 0)}; ${n(yearly?.coveragePercent ?? 0)}%<br>${n(recent?.pairedDays ?? 0, 0)} / ${n(recent?.possiblePairs ?? 0, 0)}; ${n(recent?.coveragePercent ?? 0)}%</td><td>${n(yearly?.previous.value ?? e.metrics.yearOverYear.previous.value, 0)} → ${n(yearly?.current.value ?? e.metrics.yearOverYear.current.value, 0)}</td></tr>`;
  }).join('');
  const dailyMaskNote = { uk: 'Покриття й виключені дати у таблиці стосуються денної маски. api_monthly використовує місячні агрегати цілком; ці дати не віднімаються з місячних сум.', en: 'Coverage and excluded dates describe the daily mask. api_monthly uses whole monthly aggregates; these dates are not subtracted from monthly totals.', ru: 'Покрытие и исключённые даты описывают дневную маску. api_monthly использует месячные агрегаты целиком; эти даты не вычитаются из месячных сумм.' }[locale];
  const topicCritical = a.topicStudy?.languages.map(l => `<p class="note"><strong>${h(l.language)} · core ${n(l.includedCore, 0)} / ${n(l.plannedCore, 0)}</strong>: ${h(l.conclusion)}<br>root / core / extended: ${n(l.comparisons.root)}% / ${n(l.comparisons.core)}% / ${n(l.comparisons.extended)}%. ${h(c.sensitivity)}: ${[...l.sensitivity.leaveOneOut, ...l.sensitivity.pairedMonths].filter(s => s.directionChanged || Math.abs(s.differencePoints ?? 0) >= 10).map(s => `${h(s.id)}: ${n(s.annual)}% (Δ ${n(s.differencePoints)})`).join('; ') || '—'}</p>`).join('') ?? '';
  const styles = `${fonts}\n@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}html,body{margin:0;color:#203349;font:12px/1.35 'Noto Sans',sans-serif}.report-page{width:190mm;break-after:page;padding:0}.report-page:last-child{break-after:auto}h1{font-size:22px;margin:0 0 6px}h2{font-size:14px;margin:10px 0 4px;color:#116eaa}h3{font-size:12px;margin:6px 0 3px}p{margin:4px 0;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;font-size:10.5px;table-layout:fixed}td,th{padding:4px;border-bottom:1px solid #dce5ec;text-align:right;overflow-wrap:anywhere}td:first-child,th:first-child{text-align:left;width:36%}th{background:#eef4f8}footer,.note{font-size:10px;overflow-wrap:anywhere}footer{border-top:1px solid #bdc9d4;margin-top:10px;padding-top:4px}.chart{width:710px;height:180px;margin:8px 0}.chart svg{width:710px;height:180px}.badge{color:#994911;font-weight:bold}tr{break-inside:avoid}.source-table th:first-child,.source-table td:first-child{width:7%}.source-table th:nth-child(2){width:35%}.source-table th:nth-child(3){width:18%}.source-table th:nth-child(4){width:40%}.source-table{font-size:9.5px}.source-table td{padding:3px}.source-table .note{font-size:8.5px}`;
  const html = `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:; img-src data:; script-src 'none'; connect-src 'none'; base-uri 'none'"><style>${styles}</style></head><body>
<section class="report-page"><h1>${h(t.title)}</h1><p>${h(a.topicStudy?.question ?? t.question)}</p><p class="badge">${h(a.source === 'fixtures' ? t.synthetic : t.live)}</p><p>${h(t.period)}: ${a.period.start}–${a.period.end}; ${h(t.criterion)}: ${h(t.criteria[a.criterion])}</p><p>${h(t.concepts)}: ${h(a.topics.filter(topic => main.some(e => e.topicId === topic.topicId)).map(topic => `${shorten(topic.label, 62)} [${topic.selected.map(c => c.qid).join(', ')}]`).join('; '))}</p>
${sourceTable(a, locale, 'used')}<h2>${h(c.requested)}</h2><p>${h(requested.join(', '))}. ${h(c.status)}: ${h(completion?.requestCompletion ?? 'partial')}.</p>${table(entries.filter(e => requested.includes(e.language)))}<p>${h(c.unavailable)}: ${h(completion?.unavailableLanguages.map(l => `${l.language}: ${l.code}`).join('; ') || c.none)}.</p>
<h2>${h(c.supplement)}</h2><p>${h(supplemental.join(', ') || c.none)}. ${h(c.comparison)}</p>${table(entries.filter(e => supplemental.includes(e.language)))}<p class="note">${h(c.selected)}: ${h(completion?.selectionReasons.map(r => `${r.language}: ${r.code}`).join('; ') || c.none)}</p>
${footer}</section>
<section class="report-page"><h2>${h(t.absolute)}</h2><div class="chart">${charts.absolute}</div><h2>${h(t.relative)}</h2><div class="chart">${charts.relative}</div><p class="note">${h(c.graphs)} ${h(p.rowIds.join(', '))}</p>
<h2>${h(t.metrics)}</h2><table><thead><tr><th>${h(t.row)}</th><th>${h(c.daily)}</th><th>${h(c.ppm)}</th><th>${h(c.sensitivity)}</th></tr></thead><tbody>${entries.map(e => `<tr><td>${h(title(e))}</td><td>${n(find(e, 'daily_average'))}</td><td>${n(find(e, 'relative_level'))}</td><td>${n(find(e, 'sensitivity_change'))}</td></tr>`).join('')}</tbody></table><p class="note">${h(c.full)}</p>
<h2>${h(c.quality)}</h2>${limits.map(s => `<p class="note">${h(s)}</p>`).join('')}<p class="note">${h(t.limits)}</p>${footer}</section>
<section class="report-page"><h2>${h(c.critical)}</h2><p class="note">${h(warnings.join(' · '))}</p>${topicCritical}${a.knownIssues?.map(i => `<p class="note"><a href="${h(i.source)}">${h(i.id)} (${i.period.start}–${i.period.end})</a>: ${h(i.note)}</p>`).join('') ?? ''}
<h2>${h(c.method)}</h2><table><thead><tr><th>${h(t.row)}</th><th>12 / 3</th><th>${h(c.coverage)}</th><th>${h(c.base)}</th></tr></thead><tbody>${methodRows}</tbody></table><p class="note">${h(c.methods)} ${h(dailyMaskNote)}</p><p class="note">${h(c.separate)}</p>${omittedRows.length ? `<p class="note">${h(c.omitted)}: ${h(omittedRows.join(', '))}.</p>` : ''}
<h2>${h(c.source)}</h2>${sourceTable(a, locale, 'audit')}
<h2>${h(t.validation)}</h2><p>${h(t.hypothesis)}</p><p class="note">${h(c.full)}</p>${footer}</section></body></html>`;
  requiredText.push(...warnings, ...(a.source === 'fixtures' ? [t.synthetic] : []));
  return { html, expectedNumbers, requiredText, omittedRows, omittedFindings: a.findings.filter(f => !displayedFindings.includes(f)).map(f => f.id), shortenedLabels: a.topics.filter(t => t.label.length > 62).map(t => t.topicId) };
}
