import type { Analysis } from '../analysis.js';
import type { Presentation, TemplateResult } from './template.js';
import { escapeHtml as h, formatNumber, shorten, type Locale } from './locale.js';
import type { TopicStudy } from '../topic-analysis.js';
import { sourceTable } from './source-table.js';

const copy = {
  uk: { title: 'Тематична вибірка Wikipedia', scope: 'Питання та межі вибірки', conclusion: 'Висновок із даних', metrics: 'Основні показники', components: 'Підтематики й внески', sensitivity: 'Перевірки стійкості', coverage: 'Покриття, припущення й обмеження', hypotheses: 'Напрями продуктової перевірки', sources: 'Джерела та відтворення', synthetic: 'СИНТЕТИЧНЕ OFFLINE-ДЕМО', live: 'Дані Wikimedia', views: 'Перегляди', daily: 'На день', annual: 'Рік, %', recent: '3 міс., %', normalized: 'Зміна частки, %', ppm: 'На мільйон', label: 'Набір / мова', root: 'Коренева стаття', core: 'Основний набір', extended: 'Розширений набір', contribution: 'Внесок, в.п.', change: 'Зміна, %', growth: 'Зростає / падає / ±5% / непридатні', median: 'Медіана, %', concentration: 'Частка найбільшої / трьох статей', composition: 'Склад', full: 'Повні дані: analysis.json, coverage.json, contributions.json, sensitivity.json, series.csv.', disclaimer: 'Це перегляди вибраних статей, не пошукові запити, люди, розмір ринку або доведена готовність платити.', period: 'Період', denominator: 'Нормалізація = сума набору / сума переглядів мовного розділу × 1 000 000; знаменник враховано один раз.', windows: 'Річні вікна', subset: 'Таблиця показує ключові компоненти; загальні метрики охоплюють весь оголошений придатний набір.', independent: 'Підтематики мають одну основну групу для кожної статті. Медіана й частки описують залежну вибірку; це не статистичний доказ для всієї тематики.', scenarios: 'Основні ряди незмінні. Сценарії перевіряють чутливість, не є виправленою правдою.', sameMonth: 'Без пари календарних місяців', loo: 'Без концепції', base: 'Основний результат', difference: 'Різниця, в.п.', no: 'немає даних', exclusions: 'Виключення', planCoverage: 'Покриття вибраного плану', shown: 'Показано', of: 'із', sub: 'Підтема', complete: 'Повнота', relevance: 'Відповідність питанню визначена агентом, репрезентативність не доведена.', common: 'Міжмовне порівняння використовує тільки спільний core; extended не ранжується між мовами.', current: 'Склад за поточними метаданими, не історична категорія.', heuristics: 'Евристики: напрям ±5%, мала база <1000 переглядів, матеріальна різниця ≥10 в.п.', links: 'Статті та запити API', omissions: 'Згорнуті рядки та сценарії', fixtureLinks: 'Посилання ілюструють контракт; значення синтетичні.' },
  en: { title: 'Wikipedia topic sample', scope: 'Question and sample boundaries', conclusion: 'Evidence-based conclusion', metrics: 'Main metrics', components: 'Subtopics and contributions', sensitivity: 'Sensitivity checks', coverage: 'Coverage, assumptions and limitations', hypotheses: 'Product validation directions', sources: 'Sources and reproduction', synthetic: 'SYNTHETIC OFFLINE DEMO', live: 'Wikimedia data', views: 'Views', daily: 'Per day', annual: 'Annual, %', recent: '3 months, %', normalized: 'Share change, %', ppm: 'Per million', label: 'Basket / language', root: 'Root article', core: 'Core basket', extended: 'Extended basket', contribution: 'Contribution, pp', change: 'Change, %', growth: 'Growing / declining / ±5% / unusable', median: 'Median, %', concentration: 'Largest / top three article share', composition: 'Composition', full: 'Full data: analysis.json, coverage.json, contributions.json, sensitivity.json, series.csv.', disclaimer: 'These are views of selected articles, not searches, people, market size or proven willingness to pay.', period: 'Period', denominator: 'Normalization = basket views / language edition views × 1,000,000; denominator counted once.', windows: 'Annual windows', subset: 'The table shows key components; totals cover the entire declared eligible basket.', independent: 'Each article has one primary subtopic. Medians and fractions describe a dependent sample, not statistical evidence for the entire subject.', scenarios: 'Original series remain unchanged. Scenarios test sensitivity and are not corrected truth.', sameMonth: 'Without matched calendar months', loo: 'Without concept', base: 'Baseline result', difference: 'Difference, pp', no: 'unavailable', exclusions: 'Exclusions', planCoverage: 'Selected plan coverage', shown: 'Shown', of: 'of', sub: 'Subtopic', complete: 'Completeness', relevance: 'Relevance is agent-defined; representativeness is not established.', common: 'Cross-language comparison uses the common core only; extended baskets are not ranked across languages.', current: 'Current metadata composition, not historical category membership.', heuristics: 'Heuristics: ±5% direction band, small base <1,000 views, material difference ≥10 pp.', links: 'Articles and API requests', omissions: 'Collapsed rows and scenarios', fixtureLinks: 'Links illustrate the contract; values are synthetic.' },
  ru: { title: 'Тематическая выборка Wikipedia', scope: 'Вопрос и границы выборки', conclusion: 'Вывод из данных', metrics: 'Основные показатели', components: 'Подтемы и вклады', sensitivity: 'Проверки устойчивости', coverage: 'Покрытие, предположения и ограничения', hypotheses: 'Направления продуктовой проверки', sources: 'Источники и воспроизведение', synthetic: 'СИНТЕТИЧЕСКОЕ OFFLINE-ДЕМО', live: 'Данные Wikimedia', views: 'Просмотры', daily: 'В день', annual: 'Год, %', recent: '3 мес., %', normalized: 'Изм. доли, %', ppm: 'На миллион', label: 'Набор / язык', root: 'Корневая статья', core: 'Основной набор', extended: 'Расширенный набор', contribution: 'Вклад, п.п.', change: 'Изменение, %', growth: 'Рост / спад / ±5% / непригодные', median: 'Медиана, %', concentration: 'Доля крупнейшей / трёх статей', composition: 'Состав', full: 'Полные данные: analysis.json, coverage.json, contributions.json, sensitivity.json, series.csv.', disclaimer: 'Это просмотры выбранных статей, не поисковые запросы, люди, размер рынка или доказанная готовность платить.', period: 'Период', denominator: 'Нормализация = сумма набора / сумма просмотров языкового раздела × 1 000 000; знаменатель учтён один раз.', windows: 'Годовые окна', subset: 'Таблица показывает ключевые компоненты; общие метрики охватывают весь объявленный пригодный набор.', independent: 'У каждой статьи одна основная подтема. Медиана и доли описывают зависимую выборку, не статистическое доказательство для всей тематики.', scenarios: 'Основные ряды неизменны. Сценарии проверяют чувствительность, не являются исправленной правдой.', sameMonth: 'Без пары календарных месяцев', loo: 'Без концепции', base: 'Основной результат', difference: 'Разница, п.п.', no: 'нет данных', exclusions: 'Исключения', planCoverage: 'Покрытие выбранного плана', shown: 'Показано', of: 'из', sub: 'Подтема', complete: 'Полнота', relevance: 'Соответствие вопросу определено агентом, репрезентативность не доказана.', common: 'Межъязыковое сравнение использует общий core; extended не ранжируется между языками.', current: 'Состав по текущим метаданным, не историческая категория.', heuristics: 'Эвристики: направление ±5%, малая база <1000 просмотров, существенная разница ≥10 п.п.', links: 'Статьи и запросы API', omissions: 'Свёрнутые строки и сценарии', fixtureLinks: 'Ссылки иллюстрируют контракт; значения синтетические.' },
};
function conclusion(s: TopicStudy['languages'][number], locale: Locale) {
  if (locale === 'uk') return s.conclusion;
  const en = locale === 'en', f = s.quality.flags;
  let result = s.quality.completeness === 'incomplete' ? en ? 'Insufficient coverage to generalize to the planned topic; only the fixed eligible subset is shown.' : 'Недостаточно данных для обобщения на запланированную тему; показан неизменный пригодный поднабор.'
    : s.sensitivity.directionDependsOnConcept ? en ? 'The aggregate direction depends on one article.' : 'Направление общей динамики зависит от одной статьи.'
    : s.counts.growing && s.counts.declining ? en ? 'Selected subtopics have mixed dynamics.' : 'Динамика выбранных подтем неоднородна.'
    : (s.comparisons.core ?? 0) < -5 ? en ? 'The selected basket shows declining views.' : 'В выбранном наборе просмотры снижаются.'
    : (s.comparisons.core ?? 0) > 5 ? en ? 'The selected basket shows increasing views.' : 'В выбранном наборе просмотры растут.' : en ? 'No material aggregate change within the ±5% heuristic.' : 'Существенного изменения по эвристике ±5% нет.';
  if (f.includes('ROOT_CORE_DISAGREEMENT')) result += en ? ' The root article differs from the basket.' : 'Корневая статья отличается от набора.';
  if (s.counts.growing && s.counts.declining && s.sensitivity.directionDependsOnConcept) result += en ? ' Selected subtopics have mixed dynamics.' : 'Динамика выбранных подтем неоднородна.';
  if (f.includes('EXTENDED_CORE_DISAGREEMENT')) result += en ? ' Core and extended baskets disagree.' : 'Основной и расширенный наборы расходятся.';
  if (s.sensitivity.directionDependsOnMonth) result += en ? ' Direction changes without a matched month pair.' : 'Направление меняется без пары календарных месяцев.';
  if (f.includes('NORMALIZED_CORE_DISAGREEMENT')) result += en ? ' Absolute and normalized directions disagree.' : 'Абсолютное и нормализованное направления расходятся.';
  if (f.includes('RECENT_CORE_DISAGREEMENT')) result += en ? ' Annual and recent directions disagree.' : 'Годовое и недавнее направления расходятся.';
  if (f.includes('KNOWN_DATA_ISSUE_OVERLAP')) result += en ? ' Known Wikimedia issue overlaps the period; article impact is unproven.' : 'Период пересекается с известным ограничением Wikimedia; влияние на статью не доказано.';
  return result;
}

export function buildTopicHtml(analysis: Analysis, presentation: Presentation, charts: { absolute: string; relative: string }, fonts: string): TemplateResult {
  const study = analysis.topicStudy!, locale = presentation.locale, t = copy[locale], expectedNumbers: string[] = [], requiredText: string[] = [t.title, t.conclusion, t.metrics, t.components, t.sensitivity, t.coverage, t.hypotheses, t.sources, analysis.runId];
  const shortenedLabels = new Set<string>();
  const short = (value: string, limit = 60) => { if (value.length > limit) shortenedLabels.add(value); return shorten(value, limit); };
  const n = (value: number | null, digits = 1) => { const s = formatNumber(value, locale, digits); if (value !== null) expectedNumbers.push(s); return h(s); };
  const pct = (value: number | null) => `${n(value)}${value === null ? '' : '%'}`;
  const table = (headers: string[], rows: string[][]) => `<table><thead><tr>${headers.map(x => `<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(v => `<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const section = (title: string, body: string) => `<section><h2>${h(title)}</h2>${body}</section>`;
  const p = (s: string, cls = '') => `<p class="${cls}">${s}</p>`;
  const mainRows = study.rows.filter(r => r.role === 'core'), first = mainRows[0]!, languages = study.languages;
  const labels = [...new Map(study.coverage.filter(c => c.role === 'core').map(c => [c.qid, c.label])).values()];
  const threePages = labels.length > 6 || languages.length > 1 || study.rows.some(r => r.role === 'extended') || languages.some(l => l.quality.stability !== 'stable');
  const subRows = study.rows.filter(r => r.role === 'subtopic');
  const components = languages.flatMap(l => l.contributions.map(c => ({ ...c, language: l.language }))).sort((a, b) => Math.abs(b.percentagePoints ?? 0) - Math.abs(a.percentagePoints ?? 0));
  const shown = components.slice(0, threePages ? 8 : 4);
  const main = section(t.scope, p(h(study.question)) + p(h(study.productContext), 'note') + p(h(study.boundaries), 'note') + p(`${h(t.composition)}: ${n(labels.length, 0)}; ${h([...new Set(subRows.map(r => short(r.label, 48)))].join(' · '))}. ${h(t.planCoverage)}: ${languages.map(l => `${h(l.language)} ${n(l.includedCore, 0)}/${n(l.plannedCore, 0)}`).join('; ')}.`, 'note'))
    + section(t.conclusion, languages.map(l => p(`<strong>${h(l.language)}</strong> · ${h(conclusion(l, locale))}`)).join('') + p(h(t.disclaimer), 'warning'))
    + sourceTable(analysis, locale, 'used')
    + section(t.metrics, table([t.label, t.views, t.daily, t.annual, t.recent, t.normalized], mainRows.map(r => [h(`${t.core} / ${r.language}`), n(r.metrics.totalViews.value, 0), n(r.metrics.dailyAverage.value), pct(r.metrics.yearOverYear.changePercent.value), pct(r.metrics.lastThreeMonths.changePercent.value), pct(r.metrics.yearOverYear.relativeChangePercent.value)]))
      + p(`${h(t.windows)}: ${h(first.metrics.yearOverYear.previousPeriod ? `${first.metrics.yearOverYear.previousPeriod.start} - ${first.metrics.yearOverYear.previousPeriod.end} → ${first.metrics.yearOverYear.currentPeriod!.start} - ${first.metrics.yearOverYear.currentPeriod!.end}` : t.no)}`, 'note')
      + p(`${h(t.ppm)}: ${mainRows.map(r => `${h(r.language)} ${n(r.metrics.perMillion.value)}`).join('; ')}. ${h(t.denominator)}`, 'note'))
    + `<figure>${charts.absolute}</figure>` + p(`${h(t.shown)}: ${h(presentation.rowIds.map(id => study.rows.find(r => r.id === id)?.label).join('; '))}.`, 'note')
    + p(`${h(t.common)} ${h(t.current)}`, 'note');
  const componentContent = section(t.components,
    table([t.sub, t.views, t.change], subRows.slice(0, 8).map(r => [h(`${short(r.label)} / ${r.language}`), n(r.metrics.totalViews.value, 0), pct(r.metrics.yearOverYear.changePercent.value)]))
    + p(`${h(t.shown)} ${n(Math.min(8, subRows.length), 0)} ${h(t.of)} ${n(subRows.length, 0)}. ${h(t.independent)}`, 'note')
    + table([t.label, t.change, t.contribution], shown.map(c => [h(`${short(c.label)} / ${c.language}`), pct(c.annual), n(c.percentagePoints)]))
    + p(`${h(t.shown)} ${n(shown.length, 0)} ${h(t.of)} ${n(components.length, 0)}. ${h(t.subset)}`, 'note')
    + languages.map(l => p(`${h(l.language)}: ${h(t.growth)} = ${l.counts.growing} / ${l.counts.declining} / ${l.counts.unchanged} / ${l.counts.unusable}; ${h(t.median)} ${n(l.medianChange)}; ${h(t.concentration)} ${pct(l.largestShare === null ? null : l.largestShare * 100)} / ${pct(l.topThreeShare === null ? null : l.topThreeShare * 100)}.`, 'note')).join(''))
    + section(`${t.root} / ${t.core} / ${t.extended}`, table([t.label, t.root, t.core, t.extended], languages.map(l => [h(l.language), pct(l.comparisons.root), pct(l.comparisons.core), pct(l.comparisons.extended)])));
  const scenarioContent = section(t.sensitivity, languages.map(l => {
    const loo = [...l.sensitivity.leaveOneOut].sort((a, b) => Math.abs(b.differencePoints ?? 0) - Math.abs(a.differencePoints ?? 0))[0];
    const flip = l.sensitivity.leaveOneOut.find(s => s.directionChanged);
    const month = [...l.sensitivity.pairedMonths].sort((a, b) => Math.abs(b.differencePoints ?? 0) - Math.abs(a.differencePoints ?? 0))[0];
    return p(`<strong>${h(l.language)}</strong>: ${h(t.base)} ${pct(l.comparisons.core)}.`, 'note') + table([t.label, t.change, t.difference], [
      ...(loo ? [[h(`${t.loo}: ${study.coverage.find(c => c.qid === loo.excluded[0])?.label ?? loo.excluded[0]}`), pct(loo.annual), n(loo.differencePoints)]] : []),
      ...(flip && flip.id !== loo?.id ? [[h(`${t.loo}: ${study.coverage.find(c => c.qid === flip.excluded[0])?.label ?? flip.excluded[0]}`), pct(flip.annual), n(flip.differencePoints)]] : []),
      ...(month ? [[h(`${t.sameMonth}: ${month.excluded[0]}`), pct(month.annual), n(month.differencePoints)]] : []),
    ]) + p(`${h(t.shown)} ${flip && flip.id !== loo?.id ? 3 : 2} ${h(t.of)} ${n(l.sensitivity.leaveOneOut.length + l.sensitivity.pairedMonths.length, 0)}; ${h(t.heuristics)}`, 'note');
  }).join('') + p(h(t.scenarios), 'note'));
  const excluded = study.coverage.filter(c => c.role === 'core' && !c.includedInCore);
  const coverageContent = section(t.coverage,
    p(languages.map(l => `${h(l.language)}: ${h(t.planCoverage)} ${n(l.includedCore, 0)}/${n(l.plannedCore, 0)} (${pct(l.coveragePercent)}); ${h(t.complete)}: ${h(l.quality.completeness)}.`).join(' '), 'note')
    + p(`${h(t.composition)}: ${h(labels.map(v => short(v)).join('; '))}.`, 'note')
    + p(`${h(t.exclusions)}: ${excluded.length ? h(excluded.slice(0, 6).map(c => `${short(c.label)} / ${c.language}: ${c.duplicateOf ? `duplicate ${c.duplicateOf}` : c.dataReason}`).join('; ')) : '0'}. ${h(t.shown)} ${Math.min(6, excluded.length)} ${h(t.of)} ${excluded.length}; coverage.json.`, 'note')
    + p(`${h(t.relevance)} ${h(study.assumptions.join(' '))} ${h(study.limitations.slice(0, 2).join(' '))}`, 'note')
    + study.issues.map(i => p(`<a href="${h(i.source)}">Wikimedia · ${h(i.period.start)} - ${h(i.period.end)}</a>: ${h(i.note.split('. ')[0]!)}. ${i.backfillCompleted ? `Backfill: ${h(i.backfillCompleted)}.` : ''}`, 'note')).join(''));
  const hypothesisContent = section(t.hypotheses, languages[0]!.hypotheses.slice(0, 2).map(hyp => p(`${h(short(hyp.subtopic))}: ${h(locale === 'uk' ? hyp.suggestion : locale === 'en' ? 'Test a short exercise prototype and voluntary sign-up for this subtopic; payment requires a separate test.' : 'Проверьте прототип короткого задания и добровольную заявку по этой подтеме; оплату проверяйте отдельно.')} (${h(hyp.findingId)})`, 'note')).join(''));
  const sourcesContent = section(t.sources, sourceTable(analysis, locale, 'audit')
    + p(analysis.sources.filter(s => s.url.includes('/pageviews/')).slice(0, 3).map((s, i) => `<a href="${h(s.url)}">API ${i + 1} · ${h(s.receivedAt.slice(0, 10))}</a>`).join(' · '), 'small')
    + p(`${analysis.source === 'fixtures' ? h(t.fixtureLinks) : ''} ${h(t.full)} runId: <span style="white-space:nowrap">${h(analysis.runId)}</span>; ${h(study.basketId)}; ${h(study.compositionVersion.slice(0, 12))}; methodology 3.0.0.`, 'small'));
  const shortenedNotice = shortenedLabels.size ? p(`${h(t.omissions)}: ${shortenedLabels.size} ${h(t.composition)}; ${h(t.full)}`, 'small') : '';
  const pages = threePages ? [main, componentContent + `<figure>${charts.relative}</figure>` + hypothesisContent, scenarioContent + coverageContent + shortenedNotice + sourcesContent] : [main, componentContent + scenarioContent + coverageContent + hypothesisContent + shortenedNotice + sourcesContent];
  const shownRows = new Set([...presentation.rowIds, ...mainRows.map(r => r.id), ...subRows.slice(0, 8).map(r => r.id), ...study.rows.filter(r => r.role === 'root' || r.role === 'extended' || r.role === 'concept' && shown.some(c => c.language === r.language && r.qids.includes(c.qid))).map(r => r.id)]);
  return { requiredText, expectedNumbers, omittedRows: study.rows.filter(r => !shownRows.has(r.id)).map(r => r.id), omittedFindings: analysis.findings.filter(f => !presentation.findingIds.includes(f.id)).map(f => f.id), shortenedLabels: [...shortenedLabels],
    html: `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:; img-src data:; script-src 'none'; connect-src 'none'; base-uri 'none'"><style>${fonts}
@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}html,body{margin:0;color:#203349;background:#fff;font:12px/1.4 'Noto Sans',sans-serif}main{width:190mm;margin:auto}.report-page{break-after:page}.report-page:last-child{break-after:auto}header{border-bottom:2px solid #116eaa;padding-bottom:6px;margin-bottom:9px}h1{font-size:22px;margin:0}h2{font-size:14px;color:#116eaa;margin:12px 0 5px}p{margin:5px 0;overflow-wrap:anywhere}.note{font-size:11px}.small{font-size:10px}.warning{background:#fff2df;padding:7px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}td,th{padding:5px;border-bottom:1px solid #dce5ec;text-align:right;overflow-wrap:anywhere}td:first-child,th:first-child{text-align:left;width:34%}th{background:#eef4f8}figure{margin:12px 0;width:710px;height:180px}figure svg{display:block;width:710px;height:180px}footer{border-top:1px solid #bdc9d4;margin-top:10px;padding:5px 0;font-size:10px}a{color:#116eaa}section,table,figure{break-inside:avoid}
</style></head><body><main>${pages.map((page, i) => `<div class="report-page"><header><h1>${h(t.title)}</h1><p class="note">${h(analysis.source === 'fixtures' ? t.synthetic : t.live)} · ${analysis.period.start} - ${analysis.period.end} · ${i + 1}/${pages.length}</p></header>${page}<footer>${h(study.question)} · ${i + 1}/${pages.length}</footer></div>`).join('')}</main></body></html>` };
}
